const zeBalls = [];

const FLOCK_SIZE = 256;

const MAX_X = 900;
const MAX_Y = 900;

const BALL_RADIUS = 12;
const GRAVITY = 2;
const FRICTION = 0.004;

const MAX_VELOCITY = 6 * GRAVITY;

const COZY = 8;
const COZY_DISTANCE = COZY * BALL_RADIUS;
const COZY_DISTANCE_SQ = COZY_DISTANCE * COZY_DISTANCE;
const LINE_OF_SIGHT = COZY_DISTANCE * 2;
const LINE_OF_SIGHT_SQ = LINE_OF_SIGHT * LINE_OF_SIGHT;

let tick = 0;

const ATTRACTIVE_FORCE = GRAVITY;